/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}", // ✅ all your React components & pages
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "primary-container": "#008810",
        "primary": "#006c0a",
        "secondary-container": "#026aff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006e0a",
        "secondary-fixed-dim": "#b2c5ff",
        "primary-fixed": "#85fd75",
        "on-error": "#ffffff",
        "outline-variant": "#bdcab6",
        "on-primary-container": "#f8fff0",
        "tertiary": "#954500",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#ffb68a",
        "on-secondary-fixed-variant": "#0040a1",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#005306",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "outline": "#6e7b69",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#001847",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-tertiary-fixed": "#321300",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#002201",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#743500",
        "on-secondary-container": "#fefcff",
        "on-tertiary-container": "#fffbff",
        "inverse-primary": "#69df5c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#69df5c",
        "surface": "#f7f9fb",
        "secondary-fixed": "#dae2ff",
        "secondary": "#0054cc",
        "tertiary-fixed": "#ffdbc8",
        "surface-dim": "#d8dadc",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#bb5800",
        "on-surface-variant": "#3e4a3a"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
